version: '3.3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./data:/app/data:rw
        ports:
            - '${PORT}:${PORT}'
        healthcheck:
            test: ["CMD-SHELL", "/app/healthcheck.sh"]
            interval: 2s
            timeout: 10s
            retries: 3
